/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "+ Card": "+ 卡片",
    "Auto": "自动",
    "Auto-Bot (ON)": "自动机器人 (打开)",
    "Auto-Bot (OFF)": "自动机器人 (关闭)",
    "Audio Options": "音频选项",
    "🔒 Locked": "🔒 未解锁",
    "Confirm": "确认",
    "Craft": "制作",
    "Craft Common": "制作普通",
    "DUST": "星尘",
    "Draw Card": "抽卡",
    "Equip:": "装备:",
    "Evolve 💠": "进化 💠",
    "Got it!": "我知道了!",
    "Value": "价值",
    "Upgrade Card": "升级卡片",
    "Upgrade (✨": "升级 (✨",
    "! The bar on the left fills up with each synergy and multiplies your bonus — but it drains if you stop. Manual clicks fill it faster than auto-jumps.": "! 左侧能量条会随每一次协同效果充能并放大加成——一旦停止就会持续衰减。手动点击比自动跳跃充能更快。",
    "(or more with cards!).": "（搭配卡牌效果可进一步提升！）",
    "+1 flat base income per jump per level. Scales with prestige and evolution.": "每级每次跳跃固定基础收益 +1。受声望与进化倍率加成。",
    "+1 flat income per jump": "每次跳跃固定收益 +1",
    "+1 Prestige Token awarded per prestige per level.": "每级每次声望可获得声望代币 +1。",
    "+5% chance per level for a box to jump extra high, earning x2 value.": "每级宝箱超高跳跃概率 +5%，触发时收益翻倍。",
    "Audio toggles coming in a future update!": "音效开关将在后续更新上线！",
    "Auto-Bots survive Prestige resets.": "自动机器人声望重置后保留进度。",
    "Back to Upgrades": "返回升级界面",
    "Bot Cosmic": "宇宙级机器人",
    "Bot Divine": "神圣级机器人",
    "Bot God": "神祇级机器人",
    "Bot Infinity": "无限级机器人",
    "Bot Legend": "传说级机器人",
    "Bot Overdrive": "超载级机器人",
    "Bot Supremacy": "至尊级机器人",
    "Bot Universe": "寰宇级机器人",
    "Bot Upgrade": "机器人升级",
    "Box Stats": "宝箱属性",
    "Card Shark": "卡牌高手",
    "Card Shop": "卡牌商店",
    "Card Shop Unlocked!": "卡牌商店已解锁！",
    "Cards provide": "卡牌可提供",
    "Chain": "连击",
    "Chain Cosmic": "宇宙连击",
    "Chain Divine": "神圣连击",
    "Chain Elite": "精英连击",
    "Chain Forge": "连击锻造",
    "Chain Fusion": "连击融合",
    "Chain God": "神祇连击",
    "Chain Legend": "传说连击",
    "Chain Link": "连环链接",
    "Chain Mastery": "连击精通",
    "Chain Universe": "寰宇连击",
    "Check the Card Shop button's progress bar to see when you can buy more!": "查看卡牌商店按钮进度条，即可知晓下次可购买时间！",
    "Combo Sense": "连击感知",
    "Cookie Policy": "Cookie政策",
    "Danger Zone": "危险区域",
    "Deep Timing": "深度时机",
    "Diamond Core": "钻石核心",
    "Diamond Hands": "钻石坚守",
    "Each jump counts +20% more toward prestige per level. ×3.0 at max (level 10).": "每级每次跳跃的声望进度累积值额外+20%。满级10级时倍率可达3.0倍。",
    "Eagle Eye": "鹰眼洞察",
    "Expert Hands": "巧手专精",
    "First Bot": "初始机器人",
    "Flash Overdrive": "瞬间超载",
    "Flash Steps": "瞬步疾跃",
    "Frenzy Finder": "狂热寻觅",
    "Global Talents": "全局天赋",
    "Gold Hands": "黄金巧手",
    "Have cash saved up so you can instantly re-upgrade the box after prestiging!": "提前储备资金，声望后可立即重新升级宝箱！",
    "Hawk Eye": "猎鹰之眼",
    "High Jump Crit": "高空跳跃暴击",
    "How to Play": "游戏教程",
    "Hyper Bounce": "超级弹跳",
    "If the Auto-Bot fires while a box is mid-jump, it queues and fires instantly on landing.": "若自动机器人在宝箱跳跃途中触发动作，会进入列队等待，落地瞬间立即执行。",
    "Income": "收益产出",
    "Increases Synergy window by +25ms per level.": "每级延长协同判定窗口25毫秒。",
    "Initiate Prestige": "开始声望",
    "Inventory": "背包仓库",
    "Jump Buffer": "跳跃缓冲",
    "Jump Starter": "起步增幅",
    "Keen Eye": "敏锐鹰眼",
    "Keep the synergies coming to build a": "持续触发协同效果可叠加",
    "Legal Policy": "法律政策",
    "Legend Core": "传说核心",
    "Legend Hands": "传说巧手",
    "Let's Shop!": "前往商店！",
    "Light Bounce": "轻盈弹跳",
    "Lightning Bounce": "闪电弹跳",
    "Lucky Draw": "幸运抽奖",
    "Manual Override": "手动强制操控",
    "massive x2 value bonus": "高额2倍收益加成",
    "Mastery": "精通专精",
    "Muscle Memory": "肌肉记忆",
    "Perfect Timing": "完美时机",
    "Perfect Window": "完美判定窗口",
    "Persistent Bots": "常驻机器人",
    "Phantom Blaze": "幻焰魅影",
    "Phantom Galaxy": "幻渺星河",
    "Phantom Nebula": "幻影星云",
    "Phantom Nova": "幻影新星",
    "Phantom Pulse": "幻影脉冲",
    "Phantom Quasar": "幻影类星体",
    "Phantom Rush": "幻影冲刺",
    "Phantom Step": "幻影步伐",
    "Phantom Storm": "幻影风暴",
    "Phantom Surge": "幻影涌动",
    "Phantom Touch": "幻影之触",
    "Phantom Universe": "幻影寰宇",
    "Platinum Hands": "铂金巧手",
    "Power Stride": "力量迈步",
    "powerful permanent boosts": "强力永久增幅",
    "Practice Run": "试玩模式",
    "Prestige Bonus": "声望加成",
    "Prestige Tokens:": "声望代币：",
    "Privacy Policy": "隐私政策",
    "Pro Tip:": "专业小贴士：",
    "Quantum Bot": "量子机器人",
    "Quantum Bounce": "量子弹跳",
    "Quick Bounce": "迅捷弹跳",
    "Reduces Golden Frenzy cooldown by 25% per level.": "每级减少**黄金狂热**冷却时间25%。",
    "Resets this box to earn a permanent x1.5 value multiplier and +1 PT.": "重置当前宝箱，获得永久1.5倍收益倍率并奖励1枚声望代币。",
    "Rhythm Sense": "节奏感知",
    "Scrap": "分解",
    "Scrap All": "全部分解",
    "Scrap Card?": "是否分解卡牌？",
    "Sharp Eye": "锐利鹰眼",
    "Sonic Bounce": "音速弹跳",
    "Speed": "速度",
    "Spring Boots": "弹簧靴",
    "Stats": "属性面板",
    "Steel Hands": "钢铁巧手",
    "Swift Motion": "迅捷律动",
    "Switch": "切换",
    "Switch Card?": "是否置换卡牌？",
    "Synergy": "协同联动",
    "Synergy Ascend": "协同升华",
    "Synergy Core": "协同核心",
    "Synergy Cosmic": "宇宙协同",
    "Synergy Divine": "神圣协同",
    "Synergy God": "神祇协同",
    "Synergy Infinity": "无限协同",
    "Synergy Matrix": "协同矩阵",
    "Synergy Nexus": "协同枢纽",
    "Synergy Omega": "终极协同",
    "Synergy Spark": "协同星火",
    "Synergy Universe": "寰宇协同",
    "Synergy Unlocked!": "协同效果已解锁！",
    "Talents (": "天赋系统（",
    "Targeted Draw": "定向抽取",
    "Terms of Service": "服务条款",
    "This will replace your currently equipped card. Are you sure?": "此举将替换当前已装备卡牌，是否确认？",
    "Timing Cosmic": "宇宙时序",
    "Timing Divine": "神圣时序",
    "Timing Elite": "精英时序",
    "Timing God": "神祇时序",
    "Timing Mastery": "时序精通",
    "to your boxes. Visit the shop to draw one, then equip it to a box to start earning more!": "为你的宝箱增添增益。前往商店抽取卡牌，装备到宝箱即可提升收益！",
    "Total Capital": "总资金",
    "Trained Hands": "熟练巧手",
    "Try to time your clicks so your boxes jump together!": "把握点击时机，让多个宝箱同步跳跃！",
    "Turbo Bounce": "涡轮弹跳",
    "Ultimate Hands": "终极巧手",
    "Ultra Bot": "超能机器人",
    "Unequip Card": "卸下卡牌",
    "Unlock Ghost Box": "解锁幽灵宝箱",
    "Unlocks an On/Off toggle for each box's Auto-Bot so you can manage synergies manually.": "为每个宝箱的自动机器人增加独立开关，可手动调控协同触发。",
    "Value Blizzard": "价值风雪",
    "Value Cyclone": "价值旋风",
    "Value Galaxy": "价值星河",
    "Value Hurricane": "价值飓风",
    "Value Infinity": "价值无限",
    "Value Inflation": "价值通胀",
    "Value Maelstrom": "价值乱流",
    "Value Monsoon": "价值季风",
    "Value Nebula": "价值星云",
    "Value Nova": "价值新星",
    "Value Pulsar": "价值脉冲星",
    "Value Quasar": "价值类星体",
    "Value Storm": "价值风暴",
    "Value Supernova": "价值超新星",
    "Value Surge": "价值涌动",
    "Value Tempest": "价值烈风",
    "Value Tornado": "价值龙卷",
    "Value Typhoon": "价值台风",
    "Value Universe": "价值寰宇",
    "Warp Bounce": "跃迁弹跳",
    "When two adjacent boxes jump at nearly the same time, they gain a": "当相邻两个宝箱近乎同时跳跃时，可触发",
    "Wider Synergy": "协同范围扩大",
    "Wipe Save": "清除存档",
    "Wiping your save will delete all progress, money, cards, and talents. This cannot be undone.": "清除存档将删除所有进度、金币、卡牌与天赋，且**无法撤销**。",
    "You can now afford your first Card!": "你已足够解锁第一张卡牌！",
    "You just triggered a Synergy!": "你刚刚触发了一次协同效果！",
    "No available cards to equip.": "暂无可装备的卡片。",
    "No cards drawn yet.": "暂未抽取任何卡片。",
    "COLLECT": "收集",
    "rare": "稀有",
    "Value Boost": "价值提升",
    "Upgrade": "升级",
    "Ghost Box": "幽灵宝箱",
    "Ghost Speed": "幽灵速度",
    "Ghost Sync": "幽灵同步",
    "SYNERGY READY": "协同就绪",
    "Synergy: Cooldown": "协同: 冷却",
    "PRESTIGE READY": "声望就绪",
    "common": "普通",
    "epic": "史诗",
    "Jump Speed": "跳跃速度",
    "Equipped": "已装备",
    "Scrap this COMMON card for a chance to get a rare card!": "分解这张 普通 卡片，有几率可获得一张稀有卡片！",
    "Auto-Bot": "自动机器人",
    "Scrap this RARE card for": "分解这张 稀有 卡片 ",
    "Scrap this EPIC card for": "分解这张 史诗 卡片 ",
    "Scrap this COMMON card for": "分解这张 普通 卡片 ",
    ", which is used to level up your equipped cards.": "可用于升级已装备卡牌。",
    ". Follow these strategies to maximize your wealth and climb the leaderboard.": "遵循这些玩法策略，最大化收益并冲上排行榜。",
    "← Back to Game": "← 返回游戏",
    "1. The Basics": "1. 基础玩法",
    "2. Advanced Synergy": "2. 高阶协同机制",
    "3. Card System": "3. 卡牌系统",
    "4. Prestige & Talents": "4. 声望与天赋",
    "adjacent": "相邻",
    "Auto-Bot:": "自动机器人：",
    "Automates the jumping process for passive income.": "自动完成跳跃流程，提供被动收益。",
    "Base synergy grants a": "基础协同可提供",
    "boxes jump at nearly the same time, they trigger a": "宝箱近乎同时跳跃时，会触发协同效果。",
    "Click any active box on the stage to make it jump. Each jump earns you money based on the box's": "点击场景中任意生效宝箱即可使其跳跃。每次跳跃根据宝箱**属性**获得金币收益。",
    "Draw:": "抽取：",
    "Dust": "尘屑",
    "Dust & Upgrades:": "尘屑与升级：",
    "Each box can hold one card at a time. Choose cards that complement the box's strengths.": "每个宝箱同时只能装备一张卡牌。选择适配宝箱特性的卡牌搭配。",
    "Earn 1 PT per prestige to spend on": "每次声望可获得1枚声望代币，用于兑换天赋。",
    "How to Play Poly Jump": "多边形跳跃 玩法指南",
    "Increases money earned per jump.": "提升每次跳跃获得的金币。",
    "Jump Speed:": "跳跃速度：",
    "Jumping": "跳跃",
    "Multiplier:": "倍率：",
    "Poly Jump": "多边形跳跃",
    "Prestige": "声望",
    "Prestige Tokens (PT):": "声望代币：",
    "Prestiging a box resets its individual upgrades but grants a permanent": "对宝箱进行声望会重置其单独升级，但获得永久增益。",
    "Reduces the cooldown between manual jumps.": "缩短手动跳跃的冷却间隔。",
    "Scrap unwanted cards to earn": "分解无用卡牌可获得尘屑。",
    "Spend money to draw random cards of varying rarities (Common, Rare, Epic).": "消耗金币随机抽取不同品级卡牌（普通、稀有、史诗）。",
    "stat.": "",
    "Strategy:": "策略：",
    "Synergy Bonus": "协同加成",
    "Synergy is the core mechanic of Poly Jump. When two": "协同是本作核心机制。当两个",
    "Talents:": "天赋：",
    "The Card Shop allows you to customize your boxes with powerful artifacts.": "卡牌商店可使用强力卡牌道具自定义搭配宝箱。",
    "The Reset:": "重置机制：",
    "These are permanent buffs that affect all boxes, even through resets. Focus on \"Persistent Bots\" and \"Wider Synergy\" early on!": "天赋为全局永久增益，重置进度也不会失效。前期优先点出**常驻机器人**和**协同范围扩大**！",
    "to the jump value.": "加成跳跃收益数值。",
    "Upgrades": "升级",
    "Use your earned money to upgrade three key areas:": "赚取金币可用于三大核心升级板块：",
    "Value:": "收益数值：",
    "Watch the jump timers and try to sync your clicks. Auto-Bots can also trigger synergies with your manual jumps!": "观察跳跃计时，尽量同步点击。自动机器人也能和手动跳跃触发协同！",
    "Welcome to the ultimate guide for mastering": "欢迎来到**多边形跳跃**进阶全攻略",
    "When a box reaches its jump target, it becomes eligible for": "当宝箱达到跳跃时机时，即可触发协同判定。",
    "MAX SPEED": "满级速度",
    "Common card(s) for": "普通卡片获得",
    "You are about to scrap": "你正要分解",
    "Common/Epic": "普通/史诗",
    "Common/Epic card(s) for": "普通/史诗卡片获得",
    "Common/Rare": "普通/稀有",
    "Common/Rare card(s) for": "普通/稀有卡片获得",
    "Common/Rare/Epic": "普通/稀有/史诗",
    "Common/Rare/Epic card(s) for": "普通/稀有/史诗卡片获得",
    "Epic card(s) for": "史诗卡片获得",
    "MAX SYNC": "满级协同",
    "Rare card(s) for": "稀有卡片获得",
    "Rare/Epic": "稀有/史诗",
    "Rare/Epic card(s) for": "稀有/史诗卡片获得",
    "★ MAXED": "★ 满级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "PT)": "天赋点)",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "▼": "▼",
    "▲": "▲",
    "◎": "◎",
    "⚙": "⚙",
    "⚡": "⚡",
    "⛓": "⛓",
    "✕": "✕",
    "✦": "✦",
    "✦ ✦ ✦": "✦ ✦ ✦",
    "✨": "✨",
    "⟳": "⟳",
    "👻": "👻",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\+([\d\.]+)x$/,
    /^\+([\d\.]+)ms$/,
    /^\+\$([\d\.]+)$/,
    /^\-([\d\.]+)\%$/,
    /^\-([\d\.]+)s$/,
    /^→ ([\d\.]+)s$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+\$([\d\.,]+)$/,
    /^\+\$([\d\.,]+) ⭐$/,
    /^\+\$([\d\.,]+)(.+)$/,
    /^\$([\d\.]+)(.+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\| ([\d\.]+)s$/, '| $1 秒'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)x synergy bonus$/, '+$1x 协同加成'],
    [/^\+([\d\.]+) chain scale per level$/, '每级 +$1 链式规模'],
    [/^\+([\d\.]+)\% Man Spd$/, '+$1% 手动速度'],
    [/^\+([\d\.]+)\% Val$/, '+$1% 价值'],
    [/^\+([\d\.]+)\% Auto$/, '+$1% 自动'],
    [/^\+([\d\.]+)\% Value$/, '+$1% 价值'],
    [/^\+([\d\.]+)\% Auto Spd$/, '+$1% 自动速度'],
    [/^\+([\d\.]+)\% ghost box value$/, '+$1% 幽灵宝箱价值'],
    [/^\+([\d\.]+)\% global jump value$/, '+$1% 全局跳跃价值'],
    [/^\+([\d\.]+)\% auto-bot speed$/, '+$1% 自动机器人速度'],
    [/^\+([\d\.]+)\% global Box Value per level.$/, '每级 +$1% 全局宝箱价值。'],
    [/^\+([\d\.]+)\% chance per level to draw Rare\/Epic cards.$/, '每级 +$1% 几率抽到 稀有/史诗 卡片。'],
    [/^\+([\d\.]+)\% Spd$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\-([\d\.]+)\% jump duration$/, '-$1% 跳跃持续时间'],
    [/^\-([\d\.]+)\% Card Shop pack costs per level.$/, '每级 -$1% 卡片商店卡包成本'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+)ms synergy window$/, '+$1ms 协同窗口'],
    [/^\+([\d\.,]+) flat income per jump$/, '+$1 每次跳跃所得的固定收入'],
    [/^\+([\d\.,]+)x Syn$/, '+$1x 协同'],
    [/^\+([\d\.,]+)x Syn Bonus$/, '+$1x 协同加成'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^Next Level: Lvl ([\d\.]+) \(\+([\d\.]+)\% Bonus\)$/, '下一级: 等级 $1 (+$2% 加成)'],
    [/^Next Level: Lvl ([\d\.]+) \(\+([\d\.]+)x Bonus\)$/, '下一级: 等级 $1 (+$2x 加成)'],
    [/^([\d\.,]+) PT$/, '$1 天赋点'],
    [/^✨ ([\d\.,]+) Dust$/, '✨ $1 星尘'],
    [/^([\d\.,]+) Dust$/, '$1 星尘'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^x([\d\.]+) Value Multiplier$/, 'x$1 价值乘数'],
    [/^x([\d\.]+) bonus$/, 'x$1 加成'],
    [/^Ghost Value \(([\d\.]+)\%\)$/, '幽灵价值 ($1\%)'],
    [/^Auto-Bot \(([\d\.,]+)s\)$/, '自动机器人 ($1 秒)'],
    [/^Jump Speed \(([\d\.,]+)s\)$/, '跳跃速度 ($1 秒)'],
    [/^Value \(\$([\d\.,]+)\)$/, '价值 ($ $1)'],
    [/^Common \+([\d\.,]+)✨$/, '普通 +$1✨'],
    [/^Epic \+([\d\.,]+)✨$/, '史诗 +$1✨'],
    [/^Rare \+([\d\.,]+)✨$/, '稀有 +$1✨'],
    [/^Epic ≤([\d\.,]+) draws$/, '史诗 ≤$1 抽取'],
    [/^Rare \≤([\d\.,]+) draws · Epic ≤([\d\.,]+) draws$/, '稀有 ≤$1 抽取 · 史诗 ≤$2 抽取'],
    [/^Unlock BOX ([\d\.,]+)$/, '解锁宝箱 $1'],
    [/^Evolve 💠 \(E([\d\.,]+)→E([\d\.,]+)\)$/, '进化 💠 (进化$1 → 进化$2)'],
    [/^P([\d\.,]+)$/, '声望 $1'],
    [/^E([\d\.,]+)$/, '进化 $1'],
    [/^BOX ([\d\.,]+)$/, '宝箱 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Box ([\d\.,]+)$/, '宝箱 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Jumps: (.+) \/ (.+)$/, '跳跃：$1 \/ $2'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);